"""adds profile photo column

Revision ID: cda2e882d038
Revises: 3d0c4a7401fe
Create Date: 2024-07-09 17:28:58.938072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda2e882d038'
down_revision = '3d0c4a7401fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
